# バージョンの指定
version: "3"

# サービス定義
services:
  mysql:
    container_name: ${CONTAINER_BASE_NAME}-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./docker/mysql/mysql_data:/var/lib/mysql
      - ./sql/test_data_mysql.sql:/docker-entrypoint-initdb.d/test_data_mysql.sql
  app:
    container_name: ${CONTAINER_BASE_NAME}-app
    build:
      context: ./docker
      dockerfile: app.Dockerfile
    ports:
      - "${PORT}"
    volumes:
      - ./docker/apache/htdocs/:/usr/local/apache2/htdocs/
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./mt-settings/:/usr/local/apache2/cgi-bin/mt/
      - ./mt-settings/mt-static/:/usr/local/apache2/htdocs/mt-static/
    depends_on:
      - mysql
  mailhog:
    container_name: ${CONTAINER_BASE_NAME}-mail
    image: mailhog/mailhog
    ports:
      - 8025:8025
  memcached:
    container_name: ${CONTAINER_BASE_NAME}-cache
    image: memcached:1.5.19-alpine
    ports:
      - 11211:11211
